### PR TITLE
Extract Drupal 8 module into separate branch to improve workflow

### LINKED ISSUE #2: Split module into separate repositories
At the moment we have Drupal 7.x and 8.x module in the same repository, and in different directories. I think it would be better if Drupal 7.x and 8.x modules are split into separate repositories.

### PR DESCRIPTION
**Pull request by kaittodesk**

### CODE REVIEW

**Comment by ghost** [comment]
Why did you opt to change the mysql ping logic? I can't get it working on my machine.
`app_1         | Waiting for MySQL to finish start up...
`

**Comment by kaittodesk** [comment]
I had an issue with `mysqladmin` command - for some reason it could not be found, so I opted for `mysql` command.

Is your build up to date?

**Comment by kaittodesk** [comment]
Try removing ` > /dev/null 2>&1` from line 5 in `.sandbox/bootstrap.sh` file. Then it should show you why the command is not reporting the MySQL server to be up.

**Review by ghost — APPROVED** [review]
LGTM. Got it working, don't know what the underlying cause was.

**Pull request merged**
